site_name: Финансовая грамотность
site_url: https://zaluck.github.io/financial-literacy/
site_author: ZAA
site_description: >-
  DESCRIPTION

# Repository
repo_name: zaluck/financial-literacy
repo_url: https://github.com/zaluck/financial-literacy

# nav:
#   - Home: index.md

theme:
  name: material
  # logo: img/logo.png
  # favicon: images/favicon.png
  features:
    - navigation.tabs
    - navigation.sections
    # - navigation.path
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: ru
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime


extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/zaluck
    - icon: fontawesome/brands/telegram
      link: https://telegram.org

extra_javascript:
  - javascripts/mathjax.js
  # - javascripts/tawk.js
  - https://polyfill.io/v3/polyfill.min.js #?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - search
  - social

copyright: |
  &copy; 2023 <a href="https://github.com/zaluck"  target="_blank" rel="noopener">ZAA</a>
